### ISSUE TITLE
Issue with the tutorial ControllerClass

### ISSUE THREAD

**Issue by CamKem** [laraveller/reddit-clone-with-laravel-inertiajs#1]
Hello,

I am enjoying the tutorial so far, however I have run into an issue, that you don't seem to have in the tutorial.

When i try to register a new community & then return to route 'communities.index' - I get a Laravel error in regards to the Return line.

Please have a look at the attached screenshots and hopefully you can help me...
![screen 3](https://user-images.githubusercontent.com/112100521/200531567-769e0ec0-6be4-40fa-a7be-bd6dbaf236ec.jpeg)
![screen 4](https://user-images.githubusercontent.com/112100521/200531590-f23418b2-c732-45ed-8d52-413407e4b161.jpeg)

**Comment by RensKooijman** [comment]
try :" return Redirect::route('cummunities.index');"

**Comment by CamKem** [comment]
Thanks it worked
